services:
  - type: web
    name: parish-management-system
    env: php
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm ci
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: parish-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: parish-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: parish-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: parish-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: parish-db
          property: password
      - key: APP_URL
        value: https://parish-management-system.onrender.com
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: parish-db
    plan: starter
